[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env
  | .env
  | venv
  | .venv
  | venv_gpu
  | .venv_gpu
)/
'''
line-length = 100
target-version = ['py310']

[tool.isort]
skip = [".env", "env", ".venv", "venv", "notebooks", "data", "venv_gpu", ".venv_gpu"]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100 # match our custom config above
multi_line_output = 3
float_to_top = true
use_parentheses = true